# Implementing One-Hot Encoding using Keras

## One-Hot Encoding Implementation

### Importing the library

In [3]:
import numpy as np
from tensorflow.keras.utils import to_categorical

### Creating Labels

#### &nbsp; Let's say our labels are:

*   `0` &nbsp; -> &nbsp; **Cat**
*   `2` &nbsp; -> &nbsp; **Dog**
*   `1` &nbsp; -> &nbsp; **Elephant**
*   `4` &nbsp; -> &nbsp; **Horse**
*   `3` &nbsp; -> &nbsp; **Python**

In [4]:
labels = [0, 2, 1, 4, 3]

### One-Hot Encoding our Labels

In [5]:
one_hot = to_categorical(labels)

In [6]:
print(one_hot)

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]


## One-Hot Encoding Implementation (Manual Approach)

### Creating answers and vocab Variables

In [7]:
answers = ["Kitchen", "Garden", "Office"]
vocab = ["bathroom", "garden", "kitchen", "office"]

### Helper Function (encode_answer)

In [8]:
def encode_answers(answers, vocab):

    word_to_idx = {word: idx for idx, word in enumerate(vocab)}
    encoded = np.zeros((len(answers), len(vocab)))

    for idx, answer in enumerate(answers):
        encoded[idx, word_to_idx[answer.lower()]] = 1.0

    return encoded

### Applying One-Hot Encoding

In [9]:
encoded = encode_answers(answers, vocab)

In [10]:
print(encoded)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
