# Implementing N-Grams

## Importing the libraries

In [ ]:
import pandas as pd
import numpy as np

## Creating a dataframe

In [ ]:
df = pd.DataFrame({'text':["NLP processes text data.", "Machine learning processes data.", "Deep learning processes text and data."], 'label':[0, 1, 1]})

In [ ]:
df

,text,label
0,NLP processes text data.,0
1,Machine learning processes data.,1
2,Deep learning processes text and data.,1


## Importing CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

## Uni-Gram

In [ ]:
cv = CountVectorizer(ngram_range = (1, 1))

In [ ]:
X = cv.fit_transform(df['text'])

In [ ]:
print("Unigrams:\n")
print(cv.get_feature_names_out())

Unigrams:

['and' 'data' 'deep' 'learning' 'machine' 'nlp' 'processes' 'text']


In [ ]:
X.toarray()

array([[0, 1, 0, 0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 0, 1, 1]])

## Bi-Gram

In [ ]:
cv = CountVectorizer(ngram_range = (2, 2))

In [ ]:
X = cv.fit_transform(df['text'])

In [ ]:
print("Bigrams:\n")
print(cv.get_feature_names_out())

Bigrams:

['and data' 'deep learning' 'learning processes' 'machine learning'
 'nlp processes' 'processes data' 'processes text' 'text and' 'text data']


In [ ]:
X.toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 1, 1, 0]])

## Tri Gram

In [ ]:
cv = CountVectorizer(ngram_range = (3, 3))

In [ ]:
X = cv.fit_transform(df['text'])

In [ ]:
print("Trigrams:\n")
print(cv.get_feature_names_out())

Trigrams:

['deep learning processes' 'learning processes data'
 'learning processes text' 'machine learning processes'
 'nlp processes text' 'processes text and' 'processes text data'
 'text and data']


In [ ]:
X.toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1]])

## Uni-Gram, Bi-Gram and Tri-Gram

In [ ]:
cv = CountVectorizer(ngram_range = (1, 3))

In [ ]:
X = cv.fit_transform(df['text'])

In [ ]:
print("1 - 3 Grams:\n")
print(cv.get_feature_names_out())

1 - 3 Grams:

['and' 'and data' 'data' 'deep' 'deep learning' 'deep learning processes'
 'learning' 'learning processes' 'learning processes data'
 'learning processes text' 'machine' 'machine learning'
 'machine learning processes' 'nlp' 'nlp processes' 'nlp processes text'
 'processes' 'processes data' 'processes text' 'processes text and'
 'processes text data' 'text' 'text and' 'text and data' 'text data']


In [ ]:
X.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
        1, 1, 0]])